#!/usr/bin/env python3
"""Sync publications from OpenAlex (by ORCID) into HugoBlox Academic CV content.

Pipeline
--------
1. Fetch all works for the ORCID from the OpenAlex API (free, no key, no scraping).
2. Filter: drop corrections/errata, non-paper record types (dataset/repository/…),
   and papers that share no author with a known collaborator (guards against
   same-name authors being wrongly attributed to this ORCID).
3. Deduplicate by title — the published version wins over an arXiv preprint.
4. Resolve the real venue: OpenAlex source name, falling back to Crossref's
   container-title / event name for generic series (e.g. "Lecture Notes in
   Computer Science" actually means ADMA / PAKDD / ADC / APWeb-WAIM …).
5. Enrich: author list (`me` placeholder = site owner, theme bolds it), author
   position, DOI/arXiv ids, citation count, abstract + 2-sentence summary.
6. Classify: venue -> CCF / 中科院分区 / JCR badges via scripts/venues.yml.
7. Emit one HugoBlox page per paper: content/publications/<kind>/<slug>/index.md

GENERATED FILES ARE OVERWRITTEN ON EACH RUN — do not edit them by hand.
Hand-written publications live in their own folder and are never touched.

Usage
-----
    python3 scripts/sync_publications.py --review    # 只打印评审表，不写文件
    python3 scripts/sync_publications.py --dry-run   # 列出将写入的路径
    python3 scripts/sync_publications.py             # 真正写入
"""
from __future__ import annotations

import argparse
import html
import json
import pathlib
import re
import sys
import time
import unicodedata
import urllib.parse
import urllib.request

try:
    import yaml
except ImportError:  # pragma: no cover
    sys.exit("pyyaml is required: pip install pyyaml")

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "content" / "publications"
VENUES_FILE = ROOT / "scripts" / "venues.yml"
FOLDERS = ("journal-article", "conference-paper", "preprint")
GENERATED_MARK = "GENERATED by scripts/sync_publications.py"

ORCID = "0000-0002-2032-7727"
OWN_NAMES = {"jianke yu", "yu jianke", "j. yu", "jianke  yu", "jk yu"}
# 只有与这些合作者之一同现的论文才采信（防止同名/ORCID 错误归属）
COAUTHOR_WHITELIST = {
    "Xiaoyang Wang", "Hanchen Wang", "Ying Zhang", "Lu Qin", "Wenjie Zhang",
    "Xuemin Lin", "Zhao Li", "Jian Liao", "Bailin Yang", "Chen Chen",
    "Xulu Gong", "Kecheng Wang", "Xubo Wang", "Xi Wang", "Qing Sima",
    "Min Pei", "Xianhang Zhang", "Yunkai Lou", "Shunyang Li", "Wenyuan Yu",
    "John Shepherd", "Zhengyi Yang", "Weiyuan Wang", "Xijuan Liu",
}
EXCLUDE_TITLE_RE = re.compile(r"^\s*(correction to|erratum|retraction|withdrawn)", re.I)
DROP_TYPES = {"repository", "dataset", "erratum", "editorial", "letter", "paratext",
              "peer-review", "dissertation", "libguides", "grant", "software"}
CONFERENCE_TYPES = {"conference-paper", "proceedings-article"}
GENERIC_VENUE_RE = re.compile(
    r"^(lecture notes in computer science|lncs\b|figshare|zenodo|research square|ssrn|"
    r"preprints?\.?org|openreview|arxiv \(cornell university\)|arxiv|corr\b)", re.I)
FEATURED_VENUES = {
    "IEEE Transactions on Knowledge and Data Engineering",
    "ACM SIGKDD Conference on Knowledge Discovery and Data Mining",
    "ACM SIGMOD Conference",
}
OPENALEX = "https://api.openalex.org/works"
CROSSREF = "https://api.crossref.org/works/"
UA = {"User-Agent": "jianke-homepage-sync/1.0 (mailto:yujianke100@gmail.com)"}


def http_json(url: str, tries: int = 4) -> dict:
    """GET+parse JSON with retries (OpenAlex/Crossref connections flake)."""
    last = None
    for attempt in range(tries):
        try:
            req = urllib.request.Request(url, headers=UA)
            with urllib.request.urlopen(req, timeout=60) as resp:
                return json.loads(resp.read().decode("utf-8"))
        except Exception as exc:  # noqa: BLE001 — network flake, retry then report
            last = exc
            if attempt < tries - 1:
                time.sleep(2 ** attempt * 2)
    raise RuntimeError(f"request failed after {tries} tries: {url} ({last})")


def clean(text: str | None) -> str:
    """Crossref serves doubly-escaped entities (&amp;amp;), so unescape twice."""
    out = html.unescape(html.unescape(text or ""))
    return out.replace("\u2011", "-").replace("\u00a0", " ").strip()


def fix_name(name: str) -> str:
    """OpenAlex/Crossref 偶尔返回全大写作者名（如 YING ZHANG），统一成 Title Case。"""
    n = clean(name)
    if len(n) > 3 and n.isupper():
        return " ".join(w.capitalize() for w in n.split())
    return n


def load_config() -> tuple[dict, list[tuple[re.Pattern, str]]]:
    data = yaml.safe_load(VENUES_FILE.read_text(encoding="utf-8")) or {}
    venues = {k: v for k, v in (data.get("venues") or {}).items() if isinstance(v, dict)}
    aliases = [(re.compile(a["pattern"], re.I), a["venue"]) for a in (data.get("aliases") or [])]
    return venues, aliases


def load_extras() -> list[dict]:
    """手工补充论文（已被接收但 OpenAlex 尚未收录者），转成与 OpenAlex 相同的结构。"""
    path = ROOT / "scripts" / "extra_publications.yml"
    if not path.exists():
        return []
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    works = []
    for e in data.get("papers") or []:
        venue = e.get("venue", "")
        # 走 venues.yml 判定类型：会议/期刊/预印本
        vmeta = {}
        try:
            venues, aliases = load_config()
            vmeta = venues.get(resolve_venue(venue, venues, aliases), {})
        except Exception:
            pass
        is_conf = vmeta.get("kind") == "conference" or "conference" in venue.lower()
        year = e.get("year")
        raw_date = e.get("date")
        # YAML 会把 2026-09-13 解析成 datetime.date，统一成字符串（否则与 OpenAlex 的字符串混排会崩）
        date_str = raw_date.isoformat() if hasattr(raw_date, "isoformat") else (str(raw_date) if raw_date else "")
        works.append({
            "title": e["title"],
            "publication_year": year,
            "publication_date": date_str or (f"{year}-01-01" if year else ""),
            "type": "conference-paper" if is_conf else "article",
            "authorships": [{"author": {"display_name": ("Jianke Yu" if a == "me" else a)}}
                            for a in (e.get("authors") or [])],
            "primary_location": {"source": {"display_name": venue,
                                            "type": "conference" if is_conf else "journal"}},
            "locations": [],
            "ids": {},
            "doi": f"https://doi.org/{e['doi']}" if e.get("doi") else None,
            "cited_by_count": e.get("cited_by", 0),
            "open_access": {"is_oa": False},
            "abstract_inverted_index": None,
            "_extra": True,
        })
    return works


def resolve_venue(name: str, venues: dict, aliases: list[tuple[re.Pattern, str]]) -> str:
    """Map a raw venue string to a canonical venues.yml key ('' if unmappable)."""
    if not name:
        return ""
    for key in venues:  # 1. exact
        if key.lower() == name.lower():
            return key
    for rx, canonical in aliases:  # 2. alias regex, first match wins
        if rx.search(name):
            return canonical
    for key in venues:  # 3. substring (never match on an empty needle)
        if len(name) >= 6 and (key.lower() in name.lower() or name.lower() in key.lower()):
            return key
    return ""


def fetch_works() -> list[dict]:
    works, cursor = [], "*"
    fields = ("id,doi,title,display_name,publication_year,publication_date,type,authorships,"
              "primary_location,locations,cited_by_count,abstract_inverted_index,ids,open_access")
    while cursor:
        q = urllib.parse.urlencode({"filter": f"author.orcid:{ORCID}", "per-page": "200",
                                    "cursor": cursor, "select": fields})
        data = http_json(f"{OPENALEX}?{q}")
        works.extend(data.get("results") or [])
        cursor = (data.get("meta") or {}).get("next_cursor")
        if not (data.get("results") or []):
            break
    return works


def crossref_meta(doi: str) -> tuple[list[str], str, str]:
    """Return (container titles, event name, crossref type) for a DOI."""
    if not doi:
        return [], "", ""
    try:
        msg = (http_json(CROSSREF + urllib.parse.quote(doi)) or {}).get("message") or {}
    except Exception:
        return [], "", ""
    return ([clean(x) for x in (msg.get("container-title") or [])],
            clean((msg.get("event") or {}).get("name", "")),
            msg.get("type") or "")


def venue_of(work: dict, venues: dict, aliases: list[tuple[re.Pattern, str]],
             cache: dict) -> tuple[str, str, str]:
    """Return (canonical venue, kind, raw candidate used)."""
    doi = (work.get("doi") or "").replace("https://doi.org/", "")
    src = (work.get("primary_location") or {}).get("source") or {}
    oa_name = clean(src.get("display_name", ""))
    if not oa_name:
        for loc in work.get("locations") or []:
            s = loc.get("source") or {}
            if s.get("display_name"):
                oa_name = clean(s["display_name"])
                break

    cands = [oa_name]
    if (not oa_name) or GENERIC_VENUE_RE.match(oa_name):
        if doi not in cache:
            cache[doi] = crossref_meta(doi)
        ct, event, cr_type = cache[doi]
        cands += ct + [event]
        if cr_type == "posted-content":
            cands.append("arXiv")

    canonical = ""
    for c in cands:
        if not c:
            continue
        canonical = resolve_venue(c, venues, aliases)
        if canonical:
            break
    if not canonical:  # 兜底：取第一个非泛名的原始字符串，不带徽章
        canonical = next((c for c in cands if c and not GENERIC_VENUE_RE.match(c)), "")
    raw = next((c for c in cands if c and not GENERIC_VENUE_RE.match(c)), cands[0] if cands else "")

    meta = venues.get(canonical, {})
    otype = work.get("type") or ""
    if meta.get("kind") == "preprint" or otype == "preprint" or canonical == "arXiv":
        kind = "preprint"
    elif meta.get("kind") == "conference" or otype in CONFERENCE_TYPES:
        kind = "conference"
    else:
        kind = "journal"
    return canonical, kind, raw


def authors_of(work: dict) -> tuple[list[str], int]:
    out, pos = [], 0
    for i, a in enumerate(work.get("authorships") or [], start=1):
        name = fix_name((a.get("author") or {}).get("display_name", ""))
        if name.lower() in OWN_NAMES:
            out.append("me")
            pos = pos or i
        else:
            out.append(name)
    return out, pos


def coauthor_ok(work: dict) -> bool:
    names = {fix_name((a.get("author") or {}).get("display_name", "")) for a in work.get("authorships") or []}
    return bool(names & COAUTHOR_WHITELIST)


def reconstruct_abstract(inverted: dict | None) -> str:
    if not inverted:
        return ""
    return " ".join(w for _, w in sorted((p, w) for w, ps in inverted.items() for p in ps))


def badges_for(venue_meta: dict) -> list[str]:
    """场馆等级 -> 徽章文案（英文站点，故徽章名也用英文）。会议只有 CCF，期刊再加 CAS 分区与 JCR 四分位。"""
    badges = []
    if venue_meta.get("ccf"):
        badges.append(f"CCF-{venue_meta['ccf']}")
    if venue_meta.get("kind") != "conference":
        if venue_meta.get("cas"):
            top = " Top" if venue_meta.get("cas_top") else ""
            badges.append(f"CAS Zone {venue_meta['cas']}{top}")
        if venue_meta.get("jcr"):
            badges.append(f"JCR {venue_meta['jcr']}")
    return badges


def slugify(text: str) -> str:
    text = unicodedata.normalize("NFKD", text).encode("ascii", "ignore").decode()
    return re.sub(r"[^a-zA-Z0-9]+", "-", text).strip("-").lower()[:80] or "paper"


def norm_title(t: str) -> str:
    return re.sub(r"[^a-z0-9]+", "", t.lower())


def yaml_list(items: list[str], indent: str = "  ") -> str:
    return "\n".join(f"{indent}- {json.dumps(i, ensure_ascii=False)}" for i in items)


def build_page(work: dict, venues: dict, aliases, cache: dict) -> tuple[pathlib.Path, str, dict]:
    title = clean(work.get("title") or work.get("display_name") or "")
    authors, pos = authors_of(work)
    venue, kind, raw = venue_of(work, venues, aliases, cache)
    meta = venues.get(venue, {})
    badges = badges_for(meta | {"kind": kind})
    year = work.get("publication_year") or 0
    date = work.get("publication_date") or f"{year}-01-01"
    doi = (work.get("doi") or "").replace("https://doi.org/", "")
    if doi.startswith("10.48550/arxiv."):
        doi = ""
    arxiv = ""
    for loc in work.get("locations") or []:
        if clean((loc.get("source") or {}).get("display_name", "")).lower().startswith("arxiv"):
            arxiv = (loc.get("landing_page_url") or "").split("/abs/")[-1].strip()
    abstract = reconstruct_abstract(work.get("abstract_inverted_index"))
    ptype = {"conference": "paper-conference", "journal": "article-journal", "preprint": "article"}[kind]
    folder = {"conference": "conference-paper", "journal": "journal-article", "preprint": "preprint"}[kind]
    venue_label = "arXiv preprint" if kind == "preprint" else (venue or raw or "—")
    featured = (pos == 1) and (venue in FEATURED_VENUES)

    lines = [
        "---",
        f"# ⚠️ {GENERATED_MARK} — do not edit by hand.",
    ]
    if work.get("_extra"):
        lines.append("# 来源: scripts/extra_publications.yml（已接收/发表但 OpenAlex 尚未收录，手工补充）")
    lines += [
        f"title: {json.dumps(title, ensure_ascii=False)}",
        "authors:",
        yaml_list(authors),
        f"author_position: {pos}",
        f"date: {date}",
        f"publishDate: {date}",
        f"publication_types: [{json.dumps(ptype)}]",
        "publication:",
        f"  name: {json.dumps(venue_label, ensure_ascii=False)}",
        f"  year: {year}",
        "peer_reviewed: " + ("false" if kind == "preprint" else "true"),
        f"open_access: {'true' if (work.get('open_access') or {}).get('is_oa') else 'false'}",
        f"cited_by: {work.get('cited_by_count', 0)}",
        f"featured: {'true' if featured else 'false'}",
    ]
    if badges:
        lines.append("awards:")
        for b in badges:
            lines += [f"  - name: {json.dumps(b, ensure_ascii=False)}", "    level: featured"]
    ids = ([("doi", doi)] if doi else []) + ([("arxiv", arxiv)] if arxiv else [])
    if ids:
        # 只写 hugoblox.ids：主题会据此自动生成链接（再写 links 会重复出两个 DOI 按钮）
        lines += ["hugoblox:", "  ids:"] + [f"    {k}: {v}" for k, v in ids]
    if abstract:
        lines.append(f"abstract: {json.dumps(abstract[:1800], ensure_ascii=False)}")
        lines.append("summary: " + json.dumps(" ".join(re.split(r"(?<=[.!?])\s+", abstract)[:2])[:400],
                                              ensure_ascii=False))
    lines += ["projects: []", 'slides: ""', "---", "", f"> {venue_label}, {year}", ""]
    if abstract:
        lines += [abstract, ""]

    path = OUT_DIR / folder / slugify(f"{year}-{title}") / "index.md"
    review = {"pos": pos, "kind": kind, "venue": venue or f"⚠{raw}", "year": year, "title": title,
              "badges": badges, "cited": work.get("cited_by_count", 0)}
    return path, "\n".join(lines) + "\n", review


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--review", action="store_true", help="打印评审表但不写文件")
    args = ap.parse_args()
    venues, aliases = load_config()
    works = fetch_works()
    print(f"OpenAlex: {len(works)} 条记录 (ORCID {ORCID})")

    skipped, candidates = [], []
    for w in works:
        title = clean(w.get("title") or "")
        if not title:
            continue
        if EXCLUDE_TITLE_RE.match(title):
            skipped.append((title, "勘误/撤稿"))
            continue
        if (w.get("type") or "") in DROP_TYPES:
            skipped.append((title, f"非论文记录 type={w.get('type')}"))
            continue
        if not coauthor_ok(w):
            skipped.append((title, "无已知合作者（疑似同名他人论文）"))
            continue
        candidates.append(w)

    cache: dict = {}
    best: dict[str, tuple] = {}
    for w in candidates:
        _, kind, _raw = venue_of(w, venues, aliases, cache)
        rank = (0 if kind != "preprint" else 1, -(w.get("cited_by_count") or 0))
        key = norm_title(clean(w.get("title") or ""))
        if key in best:
            skipped.append((clean(w.get("title") or ""), "标题重复（保留正式版）"))
            if rank >= best[key][0]:
                continue
        best[key] = (rank, w)

    # 手工补充（已被接收但 OpenAlex 尚未收录）：OpenAlex 已收录同名论文时不重复列出
    extras = load_extras()
    extra_added = 0
    for w in extras:
        key = norm_title(clean(w.get("title") or ""))
        if key in best:
            skipped.append((clean(w.get("title") or ""), "已由 OpenAlex 收录，忽略手工补充"))
            continue
        best[key] = ((0, 0), w)
        extra_added += 1
    if extras:
        print(f"手工补充: {len(extras)} 篇，实际新增 {extra_added} 篇")

    entries = sorted((w for _, w in best.values()),
                     key=lambda w: (w.get("publication_date") or ""), reverse=True)

    reviews, written = [], set()
    print(f"保留 {len(entries)} 篇\n")
    for w in entries:
        path, body, review = build_page(w, venues, aliases, cache)
        reviews.append(review)
        if args.review or args.dry_run:
            print(f"  [{'dry-run' if args.dry_run else 'review'}] {path.relative_to(ROOT)}")
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(body, encoding="utf-8")
        written.add(path)
        print(f"  写入 {path.relative_to(ROOT)}")

    if args.review or args.dry_run:
        print(f"\n{'位次':<4}{'类型':<11}{'场馆':<36}{'年':<6}徽章")
        for r in reviews:
            v = (r["venue"][:35] + "…") if len(r["venue"]) > 36 else r["venue"]
            star = "★一作" if r["pos"] == 1 else f"第{r['pos']}作者"
            print(f"{star:<5}{r['kind']:<11}{v:<36}{r['year']:<6}{','.join(r['badges']) or '—'}  | {r['title'][:52]}")

    if not args.dry_run and not args.review:
        keep = {p.parent / "index.md" for p in written}
        # 先收集再删除：边遍历边删目录会让 rglob 崩（FileNotFoundError）
        stale = []
        for folder in FOLDERS:
            for old in (OUT_DIR / folder).rglob("index.md"):
                if old in keep:
                    continue
                if GENERATED_MARK in old.read_text(encoding="utf-8", errors="ignore"):
                    stale.append(old)
        for old in stale:
            print(f"  清除过期生成文件 {old.relative_to(ROOT)}")
            old.unlink()
            if old.parent.exists() and not any(old.parent.iterdir()):
                old.parent.rmdir()

    unmapped = sorted({r["venue"] for r in reviews if r["venue"].startswith("⚠")})
    if unmapped:
        print("\n⚠️ 未匹配到等级规则（请补 scripts/venues.yml）：")
        for v in unmapped:
            print(f"  - {v}")
    nobadge = sorted({r["venue"] for r in reviews
                      if not r["badges"] and not r["venue"].startswith("⚠")})
    if nobadge:
        print("\nℹ️ 无 CCF 等级（目录中确实没有，或待回填中科院/JCR）：")
        for v in nobadge:
            print(f"  - {v}")
    if skipped:
        print("\n跳过的记录：")
        for t, why in skipped:
            print(f"  - [{why}] {t[:86]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
